[package]
name = "yarn-line-art"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
image = "0.24"
imageproc = "0.23"
eyre = "0.6.9"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
